### ISSUE TITLE
Bug when generating changelog.

### ISSUE THREAD

**Issue by jsi** [enonic/release-tools#20]
When Alan tries to generate a changelog, he gets this error:

```
Error details: 
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
        at org.kohsuke.github.Requester.handleApiError(Requester.java:666)
        at org.kohsuke.github.Requester._to(Requester.java:284)
        at org.kohsuke.github.Requester.to(Requester.java:225)
        at org.kohsuke.github.GitHub.getRepository(GitHub.java:421)
        at com.enonic.xp.changelog.github.GitHubServiceImpl.getRepository(GitHubServiceImpl.java:57)
        at com.enonic.xp.changelog.github.GitHubServiceImpl.<init>(GitHubServiceImpl.java:50)
        at com.enonic.xp.changelog.GenerateChangelogCommand.init(GenerateChangelogCommand.java:63)
        at com.enonic.xp.changelog.GenerateChangelogCommand.run(GenerateChangelogCommand.java:96)
        at com.enonic.xp.changelog.GenerateChangelogCommand.main(GenerateChangelogCommand.java:84)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos//
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
        at org.kohsuke.github.Requester.parse(Requester.java:597)
        at org.kohsuke.github.Requester._to(Requester.java:263)
        ... 7 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos//
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
        at org.kohsuke.github.Requester.parse(Requester.java:587)
```

**Comment by jsi** [comment]
This is the bug that comes if the git-project is checked out with https, as explained in #19 .
